### ISSUE TITLE
Add optional delay before executing modprobe

### ISSUE THREAD

**Issue by MisoMadao** [SYNwall/SYNwall_distrib#1]
If the modprobe happens very early, it may conflict with a chipset driver on raspberry.

Add a sleep before the modprobe:

`/bin/sleep XX && /bin/modprobe SYNwall`

**Comment by MisoMadao** [comment]
@cecio can we close this?

**Comment by cecio** [comment]
Yeah, I think so....gonna close!
Thanks!
